[package]
authors = ["Marcus Medom Ryding <mrok4a@gmail.com>"]
license = "AGPL-3.0+"
name = "autocrat"
readme = "README.md"
repository = "https://github.com/Magnap/autocrat"
version = "0.1.0"

[dependencies]
